# Generated by Django 5.2.7 on 2025-11-18 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('walking_time', models.IntegerField(help_text='Walking time in minutes')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_maps_url', models.URLField(blank=True, max_length=500)),
                ('icon', models.CharField(default='📍', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landmarks/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['parking_lot', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('state', models.CharField(default='Unknown', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_capacity', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parking_lots/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='parking_lots/thumbnails/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_hours', models.IntegerField(default=1)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('wallet', 'Wallet')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='PassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car (4 Wheeler)'), ('bike', 'Bike (2 Wheeler)'), ('ev', 'Electric Vehicle'), ('3w', '3 Wheeler (Auto)')], max_length=10)),
                ('duration_days', models.IntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['vehicle_type', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pricing_type', models.CharField(choices=[('hourly', 'Hourly Rate'), ('daily', 'Daily Rate'), ('weekend', 'Weekend Special'), ('holiday', 'Holiday Rate'), ('peak', 'Peak Hour Rate')], max_length=20)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car (4 Wheeler)'), ('bike', 'Bike (2 Wheeler)'), ('ev', 'Electric Vehicle'), ('3w', '3 Wheeler (Auto)')], max_length=10)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overtime_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['vehicle_type', 'pricing_type'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ParkEase', max_length=200)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('theme_color', models.CharField(default='#667eea', max_length=7)),
                ('terms_conditions', models.TextField(blank=True)),
                ('privacy_policy', models.TextField(blank=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('payment_gateway_key', models.CharField(blank=True, max_length=200)),
                ('enable_qr_entry', models.BooleanField(default=True)),
                ('enable_monthly_pass', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car (4 Wheeler)'), ('bike', 'Bike (2 Wheeler)'), ('ev', 'Electric Vehicle'), ('3w', '3 Wheeler (Auto)')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('parking_area', 'Parking Area'), ('floor_layout', 'Floor Layout'), ('slot_map', 'Slot Mapping'), ('banner', 'Home Banner'), ('facility', 'Facility')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('announcement', 'Announcement'), ('maintenance', 'Maintenance Alert'), ('payment', 'Payment Due'), ('pass_expiry', 'Pass Expiry'), ('promotion', 'Promotion/Offer')], max_length=20)),
                ('send_to_all', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParkingFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(choices=[('G', 'Ground Floor'), ('F1', 'First Floor'), ('F2', 'Second Floor'), ('F3', 'Third Floor'), ('F4', 'Fourth Floor'), ('T', 'Terrace')], max_length=10)),
                ('floor_number', models.IntegerField()),
                ('total_capacity', models.IntegerField(default=0)),
                ('is_operational', models.BooleanField(default=True)),
                ('floor_image', models.ImageField(blank=True, null=True, upload_to='floor_layouts/')),
                ('allowed_vehicle_types', models.CharField(default='car,bike,ev,3w', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('maintenance_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floors', to='parking.landmark')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='parking.parkinglot')),
            ],
            options={
                'ordering': ['parking_lot', 'floor_number'],
                'unique_together': {('parking_lot', 'floor_name')},
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=50)),
                ('block_code', models.CharField(max_length=10)),
                ('total_slots', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='parking.parkingfloor')),
            ],
            options={
                'ordering': ['floor', 'order', 'block_code'],
                'unique_together': {('floor', 'block_code')},
            },
        ),
        migrations.AddField(
            model_name='landmark',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='parking.parkinglot'),
        ),
        migrations.CreateModel(
            name='EntryExitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gate_number', models.CharField(max_length=20)),
                ('qr_scanned', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='parking.parkingsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
                ('slot_status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('slot_type', models.CharField(choices=[('small', 'Small (2W)'), ('medium', 'Medium (3W/Car)'), ('large', 'Large (SUV)'), ('ev', 'EV Charging')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('maintenance_note', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='parking.block')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='parking.parkingfloor')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.parkinglot')),
            ],
            options={
                'ordering': ['parking_lot', 'floor', 'block', 'slot_number'],
            },
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingslot'),
        ),
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=50)),
                ('zone_code', models.CharField(max_length=10)),
                ('zone_type', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP Zone'), ('ev', 'EV Zone'), ('disabled', 'Disabled Parking')], default='regular', max_length=20)),
                ('extra_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('zone_image', models.ImageField(blank=True, null=True, upload_to='zone_images/')),
                ('description', models.TextField(blank=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='parking.parkinglot')),
            ],
            options={
                'ordering': ['parking_lot', 'zone_code'],
                'unique_together': {('parking_lot', 'zone_code')},
            },
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='parking.parkingzone'),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('general', 'General Query'), ('lost', 'Lost Vehicle'), ('complaint', 'Complaint'), ('technical', 'Technical Issue'), ('payment', 'Payment Issue'), ('feedback', 'Feedback')], max_length=50)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_tickets/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle'),
        ),
        migrations.CreateModel(
            name='MonthlyPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending Approval'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_passes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_passes', to=settings.AUTH_USER_MODEL)),
                ('pass_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.passtype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together={('parking_lot', 'slot_number')},
        ),
    ]
