# Generated by Django 5.2.7 on 2025-11-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passtype',
            options={},
        ),
        migrations.RenameField(
            model_name='monthlypass',
            old_name='amount_paid',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='monthlypass',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlypass',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthlypass',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='monthlypass',
            name='parking_lots',
            field=models.ManyToManyField(related_name='monthly_passes', to='parking.parkinglot'),
        ),
        migrations.AddField(
            model_name='monthlypass',
            name='pass_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='monthlypass',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('wallet', 'Wallet'), ('cash', 'Cash')], default='cash', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlypass',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlypass',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='monthlypass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='monthlypass',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='passtype',
            name='duration_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='passtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='passtype',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', '2 Wheeler'), ('car', '4 Wheeler'), ('ev', 'Electric Vehicle'), ('3w', '3 Wheeler')], max_length=20),
        ),
    ]
