# Generated by Django 5.2.7 on 2025-11-22 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_usernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('maintenance', 'Maintenance'), ('payment', 'Payment'), ('pass_expiry', 'Pass Expiry'), ('promotion', 'Promotion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='targeted_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
