# Generated by Django 6.0 on 2025-12-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_supportticket_admin_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('wallet', 'Wallet'), ('monthly_pass', 'Monthly Pass')], default='cash', max_length=20),
        ),
    ]
