# Generated by Django 6.0 on 2025-12-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_alter_parkingsession_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='passtype',
            name='icon',
            field=models.CharField(default='🎫', max_length=10),
        ),
    ]
