# Generated by Django 6.0 on 2026-01-07 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_passtype_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('camera_type', models.CharField(choices=[('entry', 'Entry Gate'), ('exit', 'Exit Gate'), ('parking', 'Parking Area'), ('overview', 'Overview')], max_length=20)),
                ('camera_ip', models.GenericIPAddressField()),
                ('rtsp_url', models.URLField(blank=True, help_text='RTSP stream URL for live feed', max_length=500)),
                ('stream_url', models.URLField(blank=True, help_text='HTTP/HTTPS stream URL', max_length=500)),
                ('location_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('is_recording', models.BooleanField(default=True)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('installed_date', models.DateField(auto_now_add=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cctv_cameras', to='parking.parkinglot')),
            ],
            options={
                'ordering': ['parking_lot', 'camera_type', 'camera_name'],
            },
        ),
        migrations.CreateModel(
            name='CCTVFootage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footage_type', models.CharField(choices=[('entry', 'Entry Recording'), ('exit', 'Exit Recording'), ('incident', 'Incident Recording'), ('scheduled', 'Scheduled Recording')], max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='cctv_footage/%Y/%m/%d/')),
                ('snapshot_image', models.ImageField(blank=True, null=True, upload_to='cctv_snapshots/%Y/%m/%d/')),
                ('vehicle_number_detected', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('file_size_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footages', to='parking.cctvcamera')),
                ('parking_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cctv_footages', to='parking.parkingsession')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_footages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ManagerActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('entry_verify', 'Entry Verification'), ('exit_verify', 'Exit Verification'), ('manual_entry', 'Manual Entry'), ('manual_exit', 'Manual Exit'), ('booking_override', 'Booking Override'), ('slot_change', 'Slot Change'), ('incident_report', 'Incident Report'), ('camera_check', 'Camera Check')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_activities', to=settings.AUTH_USER_MODEL)),
                ('parking_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingsession')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('shift_start_time', models.TimeField(blank=True, null=True)),
                ('shift_end_time', models.TimeField(blank=True, null=True)),
                ('is_active_manager', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='manager_profiles/')),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('assigned_parking_lots', models.ManyToManyField(related_name='assigned_managers', to='parking.parkinglot')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_date'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('unauthorized_entry', 'Unauthorized Entry'), ('suspicious_vehicle', 'Suspicious Vehicle'), ('vehicle_damage', 'Vehicle Damage'), ('theft_attempt', 'Theft Attempt'), ('system_breach', 'System Breach'), ('other', 'Other Incident')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('description', models.TextField()),
                ('incident_time', models.DateTimeField()),
                ('resolved_time', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('cctv_footage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.cctvfootage')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_incidents', to='parking.parkinglot')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.vehicle')),
            ],
            options={
                'ordering': ['-incident_time'],
            },
        ),
    ]
