# Generated by Django 6.0.1 on 2026-01-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_cctvcamera_cctvfootage_manageractivitylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='ai_reason',
            field=models.CharField(blank=True, help_text='Reason for AI recommendation', max_length=255),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='ai_recommended',
            field=models.BooleanField(default=False, help_text='Was this slot AI-recommended?'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='ai_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI recommendation confidence score', max_digits=5, null=True),
        ),
    ]
